### ISSUE TITLE
User Table Redesign

### ISSUE THREAD

**Issue by BenGirone** [BenGirone/SoftwareEngineeringProject#10]
I'm changing our registration system slightly. We are removing the registration table. Please make the following changes and commit/push them to the "Register" branch:

Add the following fields to the user table:
	registrationCode  -  A varchar with the same length as the email field. not null.
	isRegistered  -  A binary value. Set default to false or 0.

I'd like this done by Thursday or Friday.

Let me know if you need any help or if you have any questions.

Explanation:
We are going to create a full non-functional user on each registration request to the server. By non-functional, I mean they exist, but cannot login. These users will be deleted after a certain amount of time if they do not finish registration.

The idea behind the new registration code is simple. A user's email is forced to be unique, so the registration code can simply be a shortened version of their e-mail with a random number appended to the end.

bgirone001@student.franciscan.edu
registrationCode = bgirone00187321

Unique and secure!

**Comment by BenGirone** [comment]
Also, the relevant Insert and Update queries will need to be updated.

**Comment by michaelolenchuk** [comment]
User Table:
Added registrationCode VARCHAR (60) NOT NULL
Added isRegistered BIT DEFAULT 0

User Input:
Added rgistrationCode
Added isRegistered
